# Welcome to the ProStaff configuration file.
# You will see that a lot of the plugin is configurable.

# Please do not touch this
config-version: 1.0

# Here you can configure all messages in the plugin. Colour codes can be used
messages:
  no-permission: '&4Error: &cYou do not have permission to execute this command!'
  sender-not-player: '&4Error: &cThis command can''t be executed from the console!'
  opened-menu: '&aOpened the staff menu'
  toggled-staff-mode: '&aToggled &lStaff Mode'